maxvalinc{

    validtest{
        controlone{
        }
        controltwo{
        }
        valueone{
            MaxValInc=58.7
        }
        valuetwo{
            value{
                MaxValInc=58.7
            }
        }
        valuethree{
            MaxValInc=23
        }
        valuefour{
            value{
                MaxValInc=23
            }
        }
        valuefive{
            MaxValInc="../controlone"
        }
        valuesix{
            value{
                MaxValInc="../../controlone"
            }
        }
        valueseven{
            MaxValInc="../controltwo"
        }
        valueeight{
            value{
                MaxValInc="../../controltwo"
            }
        }
    }
    invalidtest{
        controlone{
        }
        controltwo{
        }
        valueone{
            MaxValInc=58.7
        }
        valuetwo{
            value{
                MaxValInc=58.7
            }
        }
        valuethree{
            MaxValInc=23
        }
        valuefour{
            value{
                MaxValInc=23
            }
        }
        valuefive{
            MaxValInc="../controlone"
        }
        valuesix{
            value{
                MaxValInc="../../controlone"
            }
        }
        valueseven{
            MaxValInc="../controltwo"
        }
        valueeight{
            value{
                MaxValInc="../../controltwo"
            }
        }
    }

}
