maxvalexc{

    validtest{
        controlone{
        }
        controltwo{
        }
        valueone{
            MaxValExc=58.8
        }
        valuetwo{
            value{
                MaxValExc=58.8
            }
        }
        valuethree{
            MaxValExc=23.1
        }
        valuefour{
            value{
                MaxValExc=23.1
            }
        }
        valuefive{
            MaxValExc="../controlone"
        }
        valuesix{
            value{
                MaxValExc="../controlone"
            }
        }
        valueseven{
            MaxValExc="../controltwo"
        }
        valueeight{
            value{
                MaxValExc="../controltwo"
            }
        }
        valuenine{
            MaxValExc=NoLimit
        }
    }
    invalidtest{
        controlone{
        }
        controltwo{
        }
        valueone{
            MaxValExc=58.7
        }
        valuetwo{
            value{
                MaxValExc=58.7
            }
        }
        valuethree{
            MaxValExc=23
        }
        valuefour{
            value{
                MaxValExc=23
            }
        }
        valuefive{
            MaxValExc="../controlone"
        }
        valuesix{
            value{
                MaxValExc="../../controlone"
            }
        }
        valueseven{
            MaxValExc="../controltwo"
        }
        valueeight{
            value{
                MaxValExc="../../controltwo"
            }
        }
        valuenine{
            MaxValExc=NoLimit
        }
    }

}
