minvalinc{

    validtest{
        controlone{
        }
        controltwo{
        }
        valueone{
            MinValInc=58.7
        }
        valuetwo{
            value{
                MinValInc=58.7
            }
        }
        valuethree{
            MinValInc=23
        }
        valuefour{
            value{
                MinValInc=23
            }
        }
        valuefive{
            MinValInc="../controlone"
        }
        valuesix{
            value{
                MinValInc="../../controlone"
            }
        }
        valueseven{
            MinValInc="../controltwo"
        }
        valueeight{
            value{
                MinValInc="../../controltwo"
            }
        }
    }
    invalidtest{
        controlone{
        }
        controltwo{
        }
        valueone{
            MinValInc=58.7
        }
        valuetwo{
            value{
                MinValInc=58.7
            }
        }
        valuethree{
            MinValInc=23
        }
        valuefour{
            value{
                MinValInc=23
            }
        }
        valuefive{
            MinValInc="../controlone"
        }
        valuesix{
            value{
                MinValInc="../../controlone"
            }
        }
        valueseven{
            MinValInc="../controltwo"
        }
        valueeight{
            value{
                MinValInc="../../controltwo"
            }
        }
    }

}
