minvalexc{

    validtest{
        controlone{
        }
        controltwo{
        }
        valueone{
            MinValExc=58.7
        }
        valuetwo{
            value{
                MinValExc=58.7
            }
        }
        valuethree{
            MinValExc=23
        }
        valuefour{
            value{
                MinValExc=23
            }
        }
        valuefive{
            MinValExc="../controlone"
        }
        valuesix{
            value{
                MinValExc="../../controlone"
            }
        }
        valueseven{
            MinValExc="../controltwo"
        }
        valueeight{
            value{
                MinValExc="../../controltwo"
            }
        }
        valuenine{
            MinValExc=NoLimit
        }
    }
    invalidtest{
        controlone{
        }
        controltwo{
        }
        valueone{
            MinValExc=58.7
        }
        valuetwo{
            value{
                MinValExc=58.7
            }
        }
        valuethree{
            MinValExc=23
        }
        valuefour{
            value{
                MinValExc=23
            }
        }
        valuefive{
            MinValExc="../controlone"
        }
        valuesix{
            value{
                MinValExc="../../controlone"
            }
        }
        valueseven{
            MinValExc="../controltwo"
        }
        valueeight{
            value{
                MinValExc="../../controltwo"
            }
        }
        valuenine{
            MinValExc=NoLimit
        }
    }

}
