valtype{
    validtest{
        one{
            ValType=Int
        }
        two{
            ValType=Int
        }
        three{
            ValType=Int
        }
        four{
            ValType=Real
        }
        five{
            ValType=Real
        }
        six{
            ValType=Real
        }
        seven{
            ValType=String
        }
        eight{
            ValType=String
        }
        nine{
            ValType=RealOrQuestion
        }
        ten{
            ValType=RealOrQuestion
        }
        eleven{
            ValType=IntOrYesOrNo
        }
        twelve{
            ValType=IntOrYesOrNo
        }
        thirteen{
            ValType=IntOrYesOrNo
        }
        fourteen{
            ValType=IntOrAsterisk
        }
        fifteen{
            ValType=IntOrAsterisk
        }
        sixteen{
            ValType=Fido
        }
    }
    invalidtest{
        one{
            ValType=Int
        }
        two{
            ValType=Int
        }
        three{
            ValType=Int
        }
        four{
            ValType=Real
        }
        five{
            ValType=Real
        }
        six{
            ValType=Real
        }
        seven{
            ValType=String
        }
        eight{
            ValType=String
        }
        nine{
            ValType=RealOrQuestion
        }
        ten{
            ValType=RealOrQuestion
        }
        eleven{
            ValType=IntOrYesOrNo
        }
        twelve{
            ValType=IntOrYesOrNo
        }
        thirteen{
            ValType=IntOrYesOrNo
        }
        fourteen{
            ValType=IntOrAsterisk
        }
        fifteen{
            ValType=IntOrAsterisk
        }
        sixteen{
            ValType=BadType
        }
    }
}