test{

    controlone{
    }
    controltwo{
    }
    bad_two_numbers{
    }
    bad_string{
    }
    valueone{
        MaxValExc=58.7
    }
    valuetwo{
        value{
            MaxValExc=58.7
        }
    }
    valuethree{
        MaxValExc=23
    }
    valuefour{
        value{
            MaxValExc=23
        }
    }
    valuefive{
        MaxValExc="../controlone"
    }
    valuesix{
        value{
            MaxValExc="../../controlone"
        }
    }
    valueseven{
        MaxValExc="../controltwo"
    }
    valueeight{
        value{
            MaxValExc="../../controltwo"
        }
    }
    valuenine{
        MaxValExc=NoLimit
    }
    value_bad_one{
        inside{
            MaxValExc="../../bad_two_numbers"
        }
    }
    value_bad_two{
        inside{
            MaxValExc="../../bad_string"
        }
    }

}
